function addCSS(cssText){var style=document.createElement('style'),head=document.head||document.getElementsByTagName('head')[0];style.type='text/css';if(style.styleSheet){var func=function(){try{style.styleSheet.cssText=cssText}catch(e){}};if(style.styleSheet.disabled){setTimeout(func,10)}else{func()}}else{var textNode=document.createTextNode(cssText);style.appendChild(textNode)};head.appendChild(style)};
addCSS('#topBar{min-width:1200px;height:43px;background:#fbfbfb;position:relative;z-index:1000;font-family:"Microsoft YaHei",simSun,"Lucida Grande","Lucida Sans Unicode",Arial}#topBar #topBar_main{width:1200px;height:43px;margin:0 auto;position:relative}#topBar #topBar_main #topBar_logo{width:96px;height:35px;background:url(http://www.leiting.com/resource/terrace/images/naver/topBar_img.png?v=0820) 0 0 no-repeat;position:absolute;top:4px;left:10px;z-index:10;cursor:pointer}#topBar #topBar_main #topBar_news{width:700px;height:43px;position:absolute;top:0;left:133px;font-size:0;-webkit-text-size-adjust:none;cursor:pointer}#topBar #topBar_main #topBar_news i{width:1px;height:32px;background:#e9e9e9;display:inline-block;vertical-align:middle}#topBar #topBar_main #topBar_news #topBar_abc{width:690px;height:43px;display:inline-block;vertical-align:middle}#topBar #topBar_main #topBar_news a{width:952px;height:267px;position:absolute;top:0;left:-135px;display:none}#topBar #topBar_main #topBar_news a img{width:952px;height:267px}#topBar #topBar_main #topBar_news:hover a{display:block}#topBar #topBar_main #topBar_mid{height:43px;position:absolute;top:0;right:0;font-size:0;-webkit-text-size-adjust:none}#topBar #topBar_main #topBar_mid li{display:inline-block;vertical-align:middle;position:relative;min-width:28px;text-align:center;margin-left:60px}#topBar #topBar_main #topBar_mid li a{color:#333333;font-size:12px;line-height:43px}#topBar #topBar_main #topBar_mid li a:hover{color:#12a7eb}#topBar #topBar_main #topBar_mid #topBar_menu #topBar_game_products span{color:#12a7eb;display:inline-block;vertical-align:middle}#topBar #topBar_main #topBar_mid #topBar_menu #topBar_game_products i{width:9px;height:5px;background:url(http://www.leiting.com/resource/terrace/images/naver/topBar_img.png) -134px 0 no-repeat;display:inline-block;vertical-align:middle;margin-left:5px}#topBar #topBar_main #topBar_mid #topBar_menu #topBar_table{width:248px;min-height:195px;background:#fbfbfb;border-top:1px solid #e9e9e9;position:absolute;top:43px;right:0;zoom:1;display:none}#topBar #topBar_main #topBar_mid #topBar_menu #topBar_table:after{content:"";display:block;clear:both}#topBar #topBar_main #topBar_mid #topBar_menu:hover #topBar_table{display:block;-webkit-animation:drop .2s linear;animation:drop .2s linear}@-webkit-keyframes drop{from{opacity:0;-webkit-transform:translate3d(0,-10px,0)}to{opacity:1;-webkit-transform:translate3d(0,0,0)}}@keyframes drop{from{opacity:0;transform:translate3d(0,-10px,0)}to{opacity:1;transform:translate3d(0,0,0)}}#topBar #topBar_main #topBar_mid #topBar_menu #topBar_table .topBar_table_list{width:100%;overflow:hidden}#topBar #topBar_main #topBar_mid #topBar_menu #topBar_table .topBar_table_list a{width:124px;float:left;line-height:32px;text-align:initial}#topBar #topBar_main #topBar_mid #topBar_menu #topBar_table .topBar_table_list a i{width:11px;height:11px;display:inline-block;vertical-align:middle;margin-left:17px}#topBar #topBar_main #topBar_mid #topBar_menu #topBar_table .topBar_table_list a .topBar_n{background:url(http://www.leiting.com/resource/terrace/images/naver/topBar_img.png) -117px 0 no-repeat}#topBar #topBar_main #topBar_mid #topBar_menu #topBar_table .topBar_table_list a .topBar_h{background:url(http://www.leiting.com/resource/terrace/images/naver/topBar_img.png) -99px 0 no-repeat}#topBar #topBar_main #topBar_mid #topBar_menu #topBar_table .topBar_table_list a span{width:92px;overflow:hidden;height:32px;display:inline-block;vertical-align:middle;color:#757575;font-size:13px;text-align:left;margin-left:3px}#topBar #topBar_main #topBar_mid #topBar_menu #topBar_table .topBar_table_list a:hover span{color:#12a7eb}');
document.write('<div id="topBar">');
document.write('<div id="topBar_main">');
document.write('<a id="topBar_logo" href="http://www.leiting.com/" target="_blank"></a>');
document.write('<div id="topBar_news">');
document.write('<i></i>');
document.write('<img src="http://pic.leiting.com/upload/terrace/2022/11/21/20221121101734445.jpg "id="topBar_abc" alt="雷霆游戏会员日"/>');
document.write('<a href="http://ltc.leiting.com/landscape/index.html" target="_blank"><img src="http://pic.leiting.com/upload/terrace/2022/11/21/20221121101734690.jpg" alt="雷霆游戏会员日"/></a>');
document.write('</div>');
document.write('<ul id="topBar_mid">');
document.write('<li><a href="http://bbs.leiting.com" target="_blank">论坛</a></li>');
document.write('<li><a href="https://member.leiting.com/" target="_blank">安全</a></li>');
document.write('<li id="topBar_menu">');
document.write('<a href="javascript:;"id="topBar_game_products"><span>游戏产品</span><i></i></a>');
document.write('<div id="topBar_table">');
document.write('<div class="topBar_table_list">');
document.write('<a href="http://aobi.leiting.com/?id=M393410" target="_blank">');
document.write('<i class="topBar_h"></i>');
document.write('<span>奥比岛：梦想国度</span></a>');
document.write('<a href="http://lightning.games/en/home.html" target="_blank">');
document.write('<i class="topBar_h"></i>');
document.write('<span>Lightning Games</span></a>');
document.write('<a href="https://game.leiting.com/list/dungeon3/home" target="_blank">');
document.write('<i class="topBar_h"></i>');
document.write('<span>地下城堡3：魂之诗</span></a>');
document.write('<a href="http://game.leiting.com/list/wf" target="_blank">');
document.write('<i class="topBar_h"></i>');
document.write('<span>世界弹射物语</span></a>');
document.write('<a href="http://xian.leiting.com/?vid=ltgwlist0129" target="_blank">');
document.write('<i class="topBar_h"></i>');
document.write('<span>一念逍遥</span></a>');
document.write('<a href="http://mole.leiting.com/?vid=topbar0818" target="_blank">');
document.write('<i class="topBar_h"></i>');
document.write('<span>摩尔庄园</span></a>');
document.write('<a href="https://wd.leiting.com/" target="_blank">');
document.write('<i class="topBar_h"></i>');
document.write('<span>《问道》手游</span></a>');
document.write('<a href="https://xzysd.leiting.com/?id=M452369" target="_blank">');
document.write('<i class="topBar_n"></i>');
document.write('<span>新庄园时代</span></a>');
document.write('<a href="https://game.leiting.com/list/kairosoft/home" target="_blank">');
document.write('<i class="topBar_h"></i>');
document.write('<span>开罗游戏</span></a>');
document.write('<a href="http://game.leiting.com/list/turmoil/home" target="_blank">');
document.write('<i class="topBar_h"></i>');
document.write('<span>石油大亨</span></a>');
document.write('<a href="https://game.leiting.com/list/winter/home" target="_blank">');
document.write('<i class="topBar_h"></i>');
document.write('<span>冰原守卫者</span></a>');
document.write('<a href="http://game.leiting.com/list/em" target="_blank">');
document.write('<i class="topBar_h"></i>');
document.write('<span>恶魔秘境</span></a>');
document.write('<a href="http://game.leiting.com/list/jkxm/home" target="_blank">');
document.write('<i class="topBar_h"></i>');
document.write('<span>剑开仙门</span></a>');
document.write('<a href="https://rw.leiting.com/?id=M160409" target="_blank">');
document.write('<i class="topBar_h"></i>');
document.write('<span>复苏的魔女</span></a>');
document.write('<a href="http://game.leiting.com/list/bxzl" target="_blank">');
document.write('<i class="topBar_h"></i>');
document.write('<span>不朽之旅</span></a>');
document.write('<a href="http://myzr.leiting.com/?vid=toplist0709" target="_blank">');
document.write('<i class="topBar_h"></i>');
document.write('<span>魔渊之刃</span></a>');
document.write('<a href="https://game.leiting.com/list/yhzd" target="_blank">');
document.write('<i class="topBar_h"></i>');
document.write('<span>异化之地</span></a>');
document.write('<a href="https://elona.leiting.com/" target="_blank">');
document.write('<i class="topBar_h"></i>');
document.write('<span>伊洛纳</span></a>');
document.write('<a href="https://gumballs.leiting.com/" target="_blank">');
document.write('<i class="topBar_h"></i>');
document.write('<span>不思议迷宫</span></a>');
document.write('<a href="https://game.leiting.com/list/cave2" target="_blank">');
document.write('<i class="topBar_h"></i>');
document.write('<span>贪婪洞窟2</span></a>');
document.write('<a href="https://dxcb2.leiting.com/" target="_blank">');
document.write('<i class="topBar_h"></i>');
document.write('<span>地下城堡2</span></a>');
document.write('<a href="http://ltc.leiting.com/" target="_blank">');
document.write('<i class="topBar_h"></i>');
document.write('<span>雷霆村</span></a>');
document.write('<a href="http://game.leiting.com/list/xswc/home" target="_blank">');
document.write('<i class="topBar_h"></i>');
document.write('<span>像素危城</span></a>');
document.write('<a href="http://game.leiting.com/list/jm" target="_blank">');
document.write('<i class="topBar_h"></i>');
document.write('<span>匠木</span></a>');
document.write('<a href="http://game.leiting.com/list/wxs/home?vid=lt" target="_blank">');
document.write('<i class="topBar_h"></i>');
document.write('<span>五行师</span></a>');
document.write('<a href="http://game.leiting.com/list/qipa?vid=ltgw" target="_blank">');
document.write('<i class="topBar_h"></i>');
document.write('<span>奇葩战斗家</span></a>');
document.write('<a href="https://doll.leiting.com/" target="_blank">');
document.write('<i class="topBar_h"></i>');
document.write('<span>人偶馆绮幻夜</span></a>');
document.write('<a href="https://star.leiting.com/" target="_blank">');
document.write('<i class="topBar_h"></i>');
document.write('<span>跨越星弧</span></a>');
document.write('<a href="https://lc.leiting.com/" target="_blank">');
document.write('<i class="topBar_h"></i>');
document.write('<span>失落城堡</span></a>');
document.write('<a href="https://cave.leiting.com/" target="_blank">');
document.write('<i class="topBar_h"></i>');
document.write('<span>贪婪洞窟</span></a>');
document.write('</div></div></li></ul></div></div>');